chore(ci): Enable docs check on CI (#27)

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -35,9 +35,15 @@ jobs:
           node-version-file: .nvmrc
           cache: yarn
       - run: yarn install --immutable
-      # - run: |
-      #     yarn docs
-      #     if git diff --exit-code; then
-      #       echo "::error::The API reference docs have uncommitted changes!"
-      #       exit 1
-      #     fi
+      - run: yarn docs
+      - uses: tj-actions/verify-changed-files@v16
+        id: verify-changed-files
+        with:
+          files: |
+            **/docs/**
+      - name: Fail on missing docs
+        if: steps.verify-changed-files.outputs.files_changed == 'true'
+        run: |
+          echo "::error::The API reference docs have uncommitted changes:"
+          echo "::error::${{ steps.verify-changed-files.outputs.changed_files }}"
+          exit 1
